### ISSUE TITLE
Change the "Find Users" tab to "Users" tab

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/user-management#105]
## What is the motivation for adding/enhancing this feature?

Currently, the landing tab of the users app says "Find Users" and it's route path is also "find-users".

For better experience, Change the tab name to "Users" and also the router paths accordingly.
Also change the FindUsers component to Users component.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
issue verified and working fine in release v.1.5.2. 
https://jam.dev/c/d81127ff-48d9-4da9-bc07-2f7a6f65ab0f
