### ISSUE TITLE
Remove category security groups from Security Group Selector

### ISSUE THREAD

**Issue by dt2patel** [hotwax/user-management#111]
## What is the motivation for adding/enhancing this feature?

All security groups that are of type: PRM_CLASS_TYPE should be hidden on:

User detail page
User setup flow

During security group selection

**Comment by dt2patel** [comment]
<img width="546" alt="Screenshot 2024-02-23 at 8 35 07 PM" src="https://github.com/hotwax/user-management/assets/60128132/4b28b882-965e-4ffd-b7e3-a95e51be5031">

**Comment by amansinghbais** [comment]
Fixed this in following PR: https://github.com/hotwax/user-management/pull/100
