### ISSUE TITLE
Internal ID changes unexpectedly when renaming security group.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/user-management#115]
## Note
After the creation of security group, when we edit its name then internal ID won't gets affected/changed.

## Expected behavior
When renaming a security group, the internal ID associated with the group should remain unchanged. The internal ID serves as a unique identifier for the security group and should not be affected by changes to the group's name.

## Steps to reproduce the issue
Log in to App with valid administrative credentials.
Navigate to Permissions tab.
Click on 'CREATE SECURITY GROUP' option.
Provide a name to security group. Modify the name of the security group to a new value.
Observe the internal ID associated with the security group.

## Environment details
App version: MAIN-92E369A
App Environment: DEV

## Additional information
https://jam.dev/c/b81449c9-9b0b-4ffa-a297-802341c35a22

**Comment by dt2patel** [comment]
Do you have a jam video to attach to this? @Adameddy26

**Comment by Adameddy26** [comment]
> Do you have a jam video to attach to this? @Adameddy26

Done.

**Comment by dt2patel** [comment]
If the internal ID is generated once, it should not be updated upon change of the name field.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.7.0.
https://jam.dev/c/ae6f21e2-e580-43d6-b275-6d9f65189abb
