### ISSUE TITLE
Incorrect toast message displayed for duplicate Internal ID on security group creation.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/user-management#127]
## Expected behavior
Upon submitting the form with a duplicate internal ID, the system should display a clear and relevant toast message informing the user about the issue of duplicate internal ID. 

## Steps to reproduce the issue
Log in to the App with valid credentials.
Navigate to the security group creation interface.
Create a new security group. Enter details for a new security group, ensuring to provide a duplicate internal ID that already exists in the system.
Submit the form to create the security group.
Observe the issue.

## Environment details
App version: MAIN-92E369A
App environment: DEV

## Additional information
https://jam.dev/c/cb567813-f958-4d89-8e98-15e2386c6988

**Comment by ymaheshwari1** [comment]
@R-Sourabh pick this one.

**Comment by Adameddy26** [comment]
https://jam.dev/c/0260fff8-4fd5-43c6-b635-fcd665e2de74

Issue verified and working fine in v1.7.0. Hence, closing it.
