### ISSUE TITLE
Download option visible and blank file downloads for security group with no permissions set.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/user-management#134]
## Expected behavior
Users belonging to the security group with no permissions should not see the download option for files.

## Steps to reproduce the issue
Log in to the App with valid credentials.
Navigate to permissions section and open any security group for which no permissions are set or else create a new group with no permissions.
Observe the presence of a download option associated with the file.
Click on the download option to initiate the download process.
Verify the contents of the downloaded file.

## Environment details
App version: MAIN-92E369A
App environment: DEV

## Additional information
 https://jam.dev/c/17f8c45b-9bd3-45e1-9996-a51ece4c84f9

**Comment by dt2patel** [comment]
The option should still be there and on clicking it user will see an alert asking the user to add permissions to the security group first.

Title: No permissions associated
Description: "No permissions have been linked to this group yet. Permissions for a group cannot be downloaded.
Actions: Dimisss

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.5.2. 
https://jam.dev/c/3e3b7896-d8b8-45d6-bef9-867fed2b65bd

**Comment by Adameddy26** [comment]
Users logging into the app without initially selecting a security group encounter an issue where they are unable to download the permissions file for all groups.
Hence, reopening this issue.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.7.0.
https://jam.dev/c/161070c7-7987-43e3-99c0-29d587149c18
