### ISSUE TITLE
Tab to next input field

### ISSUE THREAD

**Issue by dt2patel** [hotwax/user-management#29]
## Current behavior

When tabbing through the user create form the tab button selects the clear input field button at the end of the input field. We either need a way to skip that or remove the clear button all together.

**Comment by dt2patel** [comment]
Concluded to remove clear button at the end of the field to allow for faster moment between input fields

**Comment by ravilodhi** [comment]
Fixed in the following PR - 
https://github.com/hotwax/user-management/pull/37
