### ISSUE TITLE
Create User Details Page: Displaying Login Details, Contact Information, and Permissions

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/user-management#3]
## What is the motivation for adding/enhancing this feature?
Currently, our system lacks a centralized user details page, making it challenging for administrators to access essential user information in one place. To address this issue, we need to create a user details page that displays login details, contact information, and permissions for each user, facilitating efficient user management and access control.

## What are the acceptance criteria?
The user details page should provide comprehensive information about each user, including login credentials, contact details, and permissions

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by k2maan** [comment]
Closing as done through - #5 #13 #16 #17
