### ISSUE TITLE
Develop New User creation feature

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/user-management#4]
## What is the motivation for adding/enhancing this feature?
Currently, our system lacks a streamlined process for creating new user accounts, both for facilities and individuals. This inefficiency hampers user onboarding and results in a time-consuming setup process. To enhance user experience and improve efficiency, we need to implement a "New User Creation" feature. This feature should allow users to create new accounts for facilities or individuals, and for individual accounts, provide quick setup templates to expedite the onboarding process.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ravilodhi** [comment]
PRs - 
https://github.com/hotwax/user-management/pull/9
https://github.com/hotwax/user-management/pull/10
https://github.com/hotwax/user-management/pull/12
