### ISSUE TITLE
Hide User Security Group Options for Users Without Change Permissions

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/user-management#44]
## What is the motivation for adding/enhancing this feature?
Currently, the user interface displays options to change the user security group for all users, regardless of their permissions.

## What are the acceptance criteria?
The user interface should only show options to change the user security group for users who have the necessary permissions to make such changes. Users without the required permissions should not be presented with these options.

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ymaheshwari1** [comment]
Closing as will be handled in https://github.com/hotwax/user-management/issues/58
