### ISSUE TITLE
Enhanced User Permissions Management

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/user-management#58]
## What is the motivation for adding/enhancing this feature?
Enhancement to the current user permissions system to provide more granular control over user creation and management. This feature aims to address specific roles and their corresponding permissions as outlined below:

- Super Users: Ability to create any type of users.
- Admin Users: Ability to create users, excluding Super Users.
- CSR (Customer Service Representative): No permission to create users, can view user information, can trigger a reset password email.
- Merchandising Manager, Order Manager, Picker: No access to the application by default (controlled by app's base level permissions)
- Excluded Roles: Warehouse Manager, Store Associate, Security Admin, Commerce User: These roles should not be available for creation or use.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ravilodhi** [comment]
@Dhiraj1405 What about the Store Manager?
