### ISSUE TITLE
Link facility modal showing virtual facilities

### ISSUE THREAD

**Issue by dt2patel** [hotwax/user-management#72]
## Current behavior

The modal to link user to facility is showing virtual facilities

<img width="1081" alt="Screenshot 2023-12-22 at 4 57 07 PM" src="https://github.com/hotwax/user-management/assets/60128132/47865f67-3587-44cf-a474-0051ca802ba3">

**Comment by ravilodhi** [comment]
This issue has been fixed under the following PR - https://github.com/hotwax/user-management/pull/69

Marking it as closed.
