### ISSUE TITLE
Create/Edit Custom User Roles 

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/user-management#87]
## What is the motivation for adding/enhancing this feature?
Currently, our system lacks the flexibility to create new custom roles or edit existing ones as per the evolving requirements of our users. To enhance user access control and meet specific needs, we need to implement a feature that allows administrators to create custom roles and modify existing ones. Additionally, we should provide users with an update on the availability of these roles.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=33983-33359&mode=design&t=QLON18CHRC9xtJxv-11

<img width="985" alt="Screenshot 2024-02-11 at 10 29 50 PM" src="https://github.com/hotwax/user-management/assets/60128132/bb046d6b-27b1-4c4d-8ff9-d4710d341081">

A new tab will be added for permission management only.

**Comment by dt2patel** [comment]
Links to create and add permissions to security group:

https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=34063-33390&mode=design&t=XBQ2IEe5XeVkb465-11

https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=34086-118161&mode=design&t=XBQ2IEe5XeVkb465-11
