### ISSUE TITLE
Password Reset Inconsistency for Users Created via Quick Setup When Accessing OMS via Direct URL

### ISSUE THREAD

**Issue by sanjanashrivastava** [hotwax/user-management#91]
## Current behavior
After using quick setup to create a new user and disabling the option 'password reset on login', one scenario is where the new user uses the launchpad to login and then accesses the OMS from the link in the launchpad. But if the new user tries logging in by using the URL of the OMS directly, the user is asked to reset the password irrespective of disabling the 'password reset on login' option. 

## Expected behavior
User should not be asked to reset password on logging in if 'password reset on login' option has been disabled irrespective of from where the OMS is accessed. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by amansinghbais** [comment]
Fixed using following PR: https://github.com/hotwax/user-management/pull/93
